// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pensioner_detail_Microservices.Models;

namespace Pensioner_detail_Microservices.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210720073742_shubham")]
    partial class shubham
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pensioner_detail_Microservices.Models.PensionerDetails", b =>
                {
                    b.Property<string>("PAN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Allowances")
                        .HasColumnType("int");

                    b.Property<string>("Dateofbirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SalaryEarned")
                        .HasColumnType("int");

                    b.Property<string>("SelforFamilypension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bank_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typeofbank")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PAN");

                    b.ToTable("Pensioners");
                });
#pragma warning restore 612, 618
        }
    }
}
